export const instruments = {
  id: 1,
  name: "Watchlist 1",
  items: [
    {
      id: "NSE:INE213A01029",
      weight: 1,
      note: null,
      tradingsymbol: "ONGC",
      instrument_token: 633601,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: 0.7,
      },
      value: 238.67,
    },
    {
      id: "NSE:INE154A01025",
      weight: 2,
      note: null,
      tradingsymbol: "ITC",
      instrument_token: 424961,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.7,
        percentage: 1.7,
      },
      value: 23.67,
    },
    {
      id: "NSE:INE155A01022",
      weight: 3,
      note: null,
      tradingsymbol: "HUDCO",
      instrument_token: 884737,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 0.67,
        percentage: -0.7,
      },
      value: 208.47,
    },
    {
      id: "NSE:INE02PY01013",
      weight: 4,
      note: null,
      tradingsymbol: "BOROLTD",
      instrument_token: 4966657,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: -0.2,
      },
      value: 123.17,
    },
    {
      id: "NSE:INE040H01021",
      weight: 5,
      note: null,
      tradingsymbol: "SUZLON",
      instrument_token: 3076609,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.34,
        percentage: 0.7,
      },
      value: 456.67,
    },
    {
      id: "NSE:INE335Y01020",
      weight: 6,
      note: null,
      tradingsymbol: "IRCTC",
      instrument_token: 3484417,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: 0.7,
      },
      value: 22.67,
    },
    {
      id: "NSE:INE053F01010",
      weight: 7,
      note: null,
      tradingsymbol: "IRFC",
      instrument_token: 519425,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 3.67,
        percentage: 1.7,
      },
      value: 894.67,
    },
    {
      id: "NSE:INE733E01010",
      weight: 8,
      note: null,
      tradingsymbol: "NTPC",
      instrument_token: 2977281,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 7,
        percentage: -5.7,
      },
      value: 9834,
    },
    {
      id: "NSE:INE202E01016",
      weight: 9,
      note: "buy if >= 177",
      tradingsymbol: "IREDA",
      instrument_token: 5186817,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 9.11,
        percentage: -2.1,
      },
      value: 186.48,
    },
    {
      id: "NSE:INE134E01011",
      weight: 10,
      note: null,
      tradingsymbol: "PFC",
      instrument_token: 3660545,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 234,
        percentage: 1.23,
      },
      value: 12565,
    },
    {
      id: "NSE:INE213A01029",
      weight: 1,
      note: null,
      tradingsymbol: "ONGC",
      instrument_token: 633601,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: 0.7,
      },
      value: 238.67,
    },
    {
      id: "NSE:INE154A01025",
      weight: 2,
      note: null,
      tradingsymbol: "ITC",
      instrument_token: 424961,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.7,
        percentage: 1.7,
      },
      value: 23.67,
    },
    {
      id: "NSE:INE155A01022",
      weight: 3,
      note: null,
      tradingsymbol: "HUDCO",
      instrument_token: 884737,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 0.67,
        percentage: -0.7,
      },
      value: 208.47,
    },
    {
      id: "NSE:INE02PY01013",
      weight: 4,
      note: null,
      tradingsymbol: "BOROLTD",
      instrument_token: 4966657,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: -0.2,
      },
      value: 123.17,
    },
    {
      id: "NSE:INE040H01021",
      weight: 5,
      note: null,
      tradingsymbol: "SUZLON",
      instrument_token: 3076609,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.34,
        percentage: 0.7,
      },
      value: 456.67,
    },
    {
      id: "NSE:INE335Y01020",
      weight: 6,
      note: null,
      tradingsymbol: "IRCTC",
      instrument_token: 3484417,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: 0.7,
      },
      value: 22.67,
    },
    {
      id: "NSE:INE053F01010",
      weight: 7,
      note: null,
      tradingsymbol: "IRFC",
      instrument_token: 519425,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 3.67,
        percentage: 1.7,
      },
      value: 894.67,
    },
    {
      id: "NSE:INE733E01010",
      weight: 8,
      note: null,
      tradingsymbol: "NTPC",
      instrument_token: 2977281,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 7,
        percentage: -5.7,
      },
      value: 9834,
    },
    {
      id: "NSE:INE202E01016",
      weight: 9,
      note: "buy if >= 177",
      tradingsymbol: "IREDA",
      instrument_token: 5186817,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 9.11,
        percentage: -2.1,
      },
      value: 186.48,
    },
    {
      id: "NSE:INE134E01011",
      weight: 10,
      note: null,
      tradingsymbol: "PFC",
      instrument_token: 3660545,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 234,
        percentage: 1.23,
      },
      value: 12565,
    },
    {
      id: "NSE:INE213A01029",
      weight: 1,
      note: null,
      tradingsymbol: "ONGC",
      instrument_token: 633601,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: 0.7,
      },
      value: 238.67,
    },
    {
      id: "NSE:INE154A01025",
      weight: 2,
      note: null,
      tradingsymbol: "ITC",
      instrument_token: 424961,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.7,
        percentage: 1.7,
      },
      value: 23.67,
    },
    {
      id: "NSE:INE155A01022",
      weight: 3,
      note: null,
      tradingsymbol: "HUDCO",
      instrument_token: 884737,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 0.67,
        percentage: -0.7,
      },
      value: 208.47,
    },
    {
      id: "NSE:INE02PY01013",
      weight: 4,
      note: null,
      tradingsymbol: "BOROLTD",
      instrument_token: 4966657,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: -0.2,
      },
      value: 123.17,
    },
    {
      id: "NSE:INE040H01021",
      weight: 5,
      note: null,
      tradingsymbol: "SUZLON",
      instrument_token: 3076609,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.34,
        percentage: 0.7,
      },
      value: 456.67,
    },
    {
      id: "NSE:INE335Y01020",
      weight: 6,
      note: null,
      tradingsymbol: "IRCTC",
      instrument_token: 3484417,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: 0.7,
      },
      value: 22.67,
    },
    {
      id: "NSE:INE053F01010",
      weight: 7,
      note: null,
      tradingsymbol: "IRFC",
      instrument_token: 519425,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 3.67,
        percentage: 1.7,
      },
      value: 894.67,
    },
    {
      id: "NSE:INE733E01010",
      weight: 8,
      note: null,
      tradingsymbol: "NTPC",
      instrument_token: 2977281,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 7,
        percentage: -5.7,
      },
      value: 9834,
    },
    {
      id: "NSE:INE202E01016",
      weight: 9,
      note: "buy if >= 177",
      tradingsymbol: "IREDA",
      instrument_token: 5186817,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 9.11,
        percentage: -2.1,
      },
      value: 186.48,
    },
    {
      id: "NSE:INE134E01011",
      weight: 10,
      note: null,
      tradingsymbol: "PFC",
      instrument_token: 3660545,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 234,
        percentage: 1.23,
      },
      value: 12565,
    },
    {
      id: "NSE:INE213A01029",
      weight: 1,
      note: null,
      tradingsymbol: "ONGC",
      instrument_token: 633601,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: 0.7,
      },
      value: 238.67,
    },
    {
      id: "NSE:INE154A01025",
      weight: 2,
      note: null,
      tradingsymbol: "ITC",
      instrument_token: 424961,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.7,
        percentage: 1.7,
      },
      value: 23.67,
    },
    {
      id: "NSE:INE155A01022",
      weight: 3,
      note: null,
      tradingsymbol: "HUDCO",
      instrument_token: 884737,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 0.67,
        percentage: -0.7,
      },
      value: 208.47,
    },
    {
      id: "NSE:INE02PY01013",
      weight: 4,
      note: null,
      tradingsymbol: "BOROLTD",
      instrument_token: 4966657,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: -0.2,
      },
      value: 123.17,
    },
    {
      id: "NSE:INE040H01021",
      weight: 5,
      note: null,
      tradingsymbol: "SUZLON",
      instrument_token: 3076609,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.34,
        percentage: 0.7,
      },
      value: 456.67,
    },
    {
      id: "NSE:INE335Y01020",
      weight: 6,
      note: null,
      tradingsymbol: "IRCTC",
      instrument_token: 3484417,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 1.67,
        percentage: 0.7,
      },
      value: 22.67,
    },
    {
      id: "NSE:INE053F01010",
      weight: 7,
      note: null,
      tradingsymbol: "IRFC",
      instrument_token: 519425,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 3.67,
        percentage: 1.7,
      },
      value: 894.67,
    },
    {
      id: "NSE:INE733E01010",
      weight: 8,
      note: null,
      tradingsymbol: "NTPC",
      instrument_token: 2977281,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 7,
        percentage: -5.7,
      },
      value: 9834,
    },
    {
      id: "NSE:INE202E01016",
      weight: 9,
      note: "buy if >= 177",
      tradingsymbol: "IREDA",
      instrument_token: 5186817,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 9.11,
        percentage: -2.1,
      },
      value: 186.48,
    },
    {
      id: "NSE:INE134E01011",
      weight: 10,
      note: null,
      tradingsymbol: "PFC",
      instrument_token: 3660545,
      segment: "NSE",
      exchange: "NSE",
      expiry: "",
      dayChange: {
        value: 234,
        percentage: 1.23,
      },
      value: 12565,
    },
  ],
};

export const userHoldings = [
  {
    tradingSymbol: "HUDCO",
    quantity: 10,
    avgCost: 227.39,
    ltp: 208.45,
    invested: 2273.92,
    currValue: 2084.5,
    pnl: -189.42,
    netChg: -8.33,
    dayChg: -1.42,
  },
  {
    tradingSymbol: "IREDA",
    quantity: 5,
    avgCost: 176.2,
    ltp: 156.48,
    invested: 881,
    currValue: 782.4,
    pnl: -98.6,
    netChg: -11.19,
    dayChg: -1.45,
  },
];

export const userPnL = {
  totalInvestment: 3154.92,
  currentValue: 2873.4,
  dayPnL: {
    value: 35.05,
    percentage: 1.21,
  },
  totalPnL: {
    value: -281.52,
    percentage: -8.92,
  },
};

export const USER_PNL_MAPPING = {
  totalInvestment: "Total investment",
  currentValue: "Current value",
  dayPnL: "Day's P&L",
  totalPnL: "Total P&L",
};
