export const mockData = [
    {
        title: "Rahul Goel",
        subtitle: "Vice President",
        team: "Tech",
        id: 1,
        manager: null,
        img: "/assets/images/employees/emp1.jpeg",
    },
    {
        title: "Sahil",
        subtitle: "Engineering Manager",
        team: "Tech",
        id: 2,
        manager: 1,
        img: "/assets/images/employees/emp2.jpeg",
    },
    {
        title: "Shreedar",
        subtitle: "Tech Lead",
        team: "Tech",
        id: 3,
        manager: 1,
        img: "/assets/images/employees/emp3.jpeg",
    },
    {
        title: "Ayas",
        subtitle: "Junior Developer",
        team: "Tech",
        id: 39,
        manager: 3,
        img: "/assets/images/employees/emp3.jpeg",
    },
    {
        title: "Vikas",
        subtitle: "Tech Lead",
        team: "Tech",
        id: 4,
        manager: 2,
        img: "/assets/images/employees/emp4.jpeg",
    },
    {
        title: "Hritik",
        subtitle: "Senior Developer",
        team: "Tech",
        id: 5,
        manager: 4,
        img: "/assets/images/employees/emp6.jpg",
    },
    {
        title: "Intel",
        subtitle: "Senior Developer",
        team: "Tech",
        id: 6,
        manager: 4,
        img: "/assets/images/employees/emp5.jpg",
    },
    {
        title: "Rahul Gupta",
        subtitle: "Senior Developer",
        team: "Tech",
        id: 7,
        manager: 4,
        img: "/assets/images/employees/emp7.jpg",
    },
    {
        title: "Rohan Gupta",
        subtitle: "Senior Developer",
        team: "Tech",
        id: 8,
        manager: 6,
        img: "/assets/images/employees/emp1.jpeg",
    },

    {
        title: "Mohit",
        subtitle: "Design Manager",
        team: "Design",
        id: 9,
        manager: null,
        img: "/assets/images/employees/emp2.jpeg",
    },
    {
        title: "Sam",
        subtitle: "Senior Designer",
        team: "Design",
        id: 10,
        manager: 9,
        img: "/assets/images/employees/emp3.jpeg",
    },
    {
        title: "Sanchi",
        subtitle: "Junior Designer",
        team: "Design",
        id: 11,
        manager: 9,
        img: "/assets/images/employees/emp4.jpeg",
    },

    {
        title: "Anand",
        subtitle: "Product Manager",
        team: "Product",
        id: 12,
        manager: null,
        img: "/assets/images/employees/emp5.jpg",
    },
    {
        title: "Ram",
        subtitle: "Product Lead",
        team: "Product",
        id: 13,
        manager: 12,
        img: "/assets/images/employees/emp6.jpg",
    },
    {
        title: "Nameesh",
        subtitle: "Product Analyst",
        team: "Product",
        id: 14,
        manager: 13,
        img: "/assets/images/employees/emp7.jpg",
    },
    {
        title: "Deepak",
        subtitle: "Product Specialist",
        team: "Product",
        id: 15,
        manager: 13,
        img: "/assets/images/employees/emp1.jpeg",
    },
    {
        title: "Rahul Singla",
        subtitle: "Senior Product Analyst",
        team: "Product",
        id: 16,
        manager: 14,
        img: "/assets/images/employees/emp2.jpeg",
    },
    {
        title: "Rahul Jha",
        subtitle: "Junior Product Analyst",
        team: "Product",
        id: 17,
        manager: 16,
        img: "/assets/images/employees/emp3.jpeg",
    },
    {
        title: "Hemanth Kumar",
        subtitle: "Product Researcher",
        team: "Product",
        id: 18,
        manager: 15,
        img: "/assets/images/employees/emp4.jpeg",
    },

    {
        title: "Rajesh",
        subtitle: "Business Manager",
        team: "Business",
        id: 19,
        manager: null,
        img: "/assets/images/employees/emp5.jpg",
    },
    {
        title: "Yashwanth",
        subtitle: "Business Lead",
        team: "Business",
        id: 20,
        manager: 19,
        img: "/assets/images/employees/emp6.jpg",
    },
    {
        title: "Raj",
        subtitle: "Business Analyst",
        team: "Business",
        id: 21,
        manager: 20,
        img: "/assets/images/employees/emp7.jpg",
    },
    {
        title: "Sumit",
        subtitle: "Business Associate",
        team: "Business",
        id: 22,
        manager: 20,
        img: "/assets/images/employees/emp1.jpeg",
    },
    {
        title: "Ravi",
        subtitle: "Business Coordinator",
        team: "Business",
        id: 23,
        manager: 22,
        img: "/assets/images/employees/emp2.jpeg",
    },
];
